// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQy8NrpCMhCaYxQTNmgapJzsu8nEbC2I',
    appId: '1:990736978525:web:93714c641113347b3b73b4',
    messagingSenderId: '990736978525',
    projectId: 'thelazycloset',
    authDomain: 'thelazycloset.firebaseapp.com',
    storageBucket: 'thelazycloset.appspot.com',
    measurementId: 'G-C01PLJ9P8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHORKm1bbI5mmEAOMQ7XMOwuLrhfeTUEI',
    appId: '1:990736978525:android:c489278c7249c0ec3b73b4',
    messagingSenderId: '990736978525',
    projectId: 'thelazycloset',
    storageBucket: 'thelazycloset.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnyu8atnj2U2fv3NtP9o7dlm0iU7bkDiY',
    appId: '1:990736978525:ios:f90f7a090724547d3b73b4',
    messagingSenderId: '990736978525',
    projectId: 'thelazycloset',
    storageBucket: 'thelazycloset.appspot.com',
    iosClientId: '990736978525-knhslktqntop6jacqceoj14pm4b5j5rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.thelazycloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnyu8atnj2U2fv3NtP9o7dlm0iU7bkDiY',
    appId: '1:990736978525:ios:aa2404fa69d9d3c33b73b4',
    messagingSenderId: '990736978525',
    projectId: 'thelazycloset',
    storageBucket: 'thelazycloset.appspot.com',
    iosClientId: '990736978525-17cmau8nvam3v0d1b92a99rp8af9l3f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.thelazycloset.RunnerTests',
  );
}
